import { execFileSync, spawn } from "node:child_process";
import crypto from "node:crypto";
import { once } from "node:events";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import Database from "better-sqlite3";
import { afterEach, describe, expect, it, vi } from "vitest";

import { applyRetirement, previewRetirement } from "../scripts/retire-legacy-state.js";

const roots: string[] = [];
const legacySource = execFileSync(
  "git",
  ["show", "93781d700a50dd893ac54641c57855e4726f4e67:src/db/index.ts"],
  { encoding: "utf8", cwd: path.resolve(import.meta.dirname, "..") }
);
const legacySql = /sqlite\.exec\(`([\s\S]*?)`\);/.exec(legacySource)![1]!;
const target = "targets/example-0123456789abcdef";
const database = `${target}/agent-ops.db`;
const firstReport = `${target}/reports/20260909T060000Z-1-readiness-sweep.md`;
const secondReport = `${target}/reports/20260909T060001Z-2-readiness-sweep.md`;
const reportBody =
  "# Agent Readiness Sweep\n\nRepository: `/synthetic/repo`\n\nThis report was generated by Agent Ops Kit through a read-only workflow.\n\nFixture\n";

function temporaryRoot() {
  const root = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), "legacy-retirement-")));
  roots.push(root);
  return root;
}

function write(root: string, relative: string, body: string | Buffer) {
  const file = path.join(root, relative);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, body);
  return file;
}

function legacyFixture() {
  const root = temporaryRoot();
  fs.mkdirSync(path.join(root, target), { recursive: true });
  const db = new Database(path.join(root, database));
  db.exec(legacySql);
  db.exec(`
    INSERT INTO repository (name, local_path) VALUES ('synthetic', '/synthetic/repo');
    INSERT INTO task (stable_key, repository_id, type, title, objective)
      VALUES ('repo-readiness:1', 1, 'repo_readiness_sweep', 'Fixture', 'Fixture');
    INSERT INTO run (task_id) VALUES (1), (1);
  `);
  db.close();
  write(root, firstReport, reportBody);
  return root;
}

function reseal(manifest: ReturnType<typeof previewRetirement>) {
  const body = { ...manifest, digest: undefined };
  delete body.digest;
  return {
    ...body,
    digest: crypto.createHash("sha256").update(JSON.stringify(body)).digest("hex")
  };
}

async function withDatabaseHolder(root: string, transaction: string, test: () => void) {
  const child = spawn(
    process.execPath,
    [
      "--input-type=module",
      "-e",
      `
    import Database from "better-sqlite3";
    const db = new Database(process.argv[1]);
    db.exec(process.argv[2]);
    process.send("ready");
    setInterval(() => { if (!db.open) process.exit(1); }, 1000);
  `,
      path.join(root, database),
      transaction
    ],
    {
      cwd: path.resolve(import.meta.dirname, ".."),
      stdio: ["ignore", "ignore", "pipe", "ipc"]
    }
  );
  try {
    await new Promise<void>((resolve, reject) => {
      const timer = setTimeout(() => reject(new Error("SQLite holder did not become ready")), 5000);
      child.once("message", () => {
        clearTimeout(timer);
        resolve();
      });
      child.once("error", (error) => {
        clearTimeout(timer);
        reject(error);
      });
      child.once("exit", (code) => {
        clearTimeout(timer);
        reject(new Error(`SQLite holder exited: ${code}`));
      });
    });
    test();
  } finally {
    if (child.exitCode === null && child.signalCode === null) {
      const exited = once(child, "exit");
      child.kill("SIGTERM");
      await exited;
    }
  }
}

afterEach(() => {
  vi.restoreAllMocks();
  vi.unstubAllEnvs();
  for (const root of roots.splice(0)) fs.rmSync(root, { recursive: true, force: true });
});

describe("legacy-state retirement", () => {
  it("previews without creating state and requires stopped writers before apply", () => {
    const root = temporaryRoot();
    const manifest = previewRetirement(root);
    expect(manifest.files).toEqual([]);
    expect(fs.readdirSync(root)).toEqual([]);
    expect(() => applyRetirement(root, manifest, false)).toThrow("--writers-stopped");
  });

  it("previews unchanged bytes and removes only recognized legacy files, database last", () => {
    const root = legacyFixture();
    const preserved = [
      "history/agent-ops.db",
      "history/artifacts/report.md",
      "cache/git/source.ts",
      "workspaces/checkout/.env",
      ".env",
      `${target}/.env`,
      `${target}/unknown.db`,
      `${target}/reports/notes.md`,
      `${target}/reports/20260909T060002Z-3-readiness-sweep.md`,
      `${target}/reports/arbitrary.md`,
      `${target}/nested/agent-ops.db`
    ];
    for (const file of preserved)
      write(root, file, file.endsWith("arbitrary.md") ? reportBody : "preserve me");
    const legacyFiles = [
      firstReport,
      `${database}-journal`,
      `${database}-wal`,
      `${database}-shm`,
      database
    ];
    for (const suffix of ["-journal", "-wal", "-shm"])
      write(root, `${database}${suffix}`, Buffer.alloc(32));
    const before = new Map(
      [...preserved, ...legacyFiles].map((file) => [file, fs.readFileSync(path.join(root, file))])
    );
    const manifest = previewRetirement(root);
    expect(new Set(manifest.files.map((file) => file.path))).toEqual(new Set(legacyFiles));
    expect(manifest.excluded.map((file) => file.path)).toContain(`${target}/reports/notes.md`);
    for (const [file, contents] of before)
      expect(fs.readFileSync(path.join(root, file)).equals(contents), file).toBe(true);
    const unlink = vi.spyOn(fs, "unlinkSync");
    const result = applyRetirement(root, manifest, true);
    expect(result).toMatchObject({ ok: true, remaining: [] });
    expect(unlink.mock.calls.at(-1)?.[0]).toBe(path.join(root, database));
    for (const file of legacyFiles) expect(fs.existsSync(path.join(root, file))).toBe(false);
    for (const file of preserved)
      expect(fs.readFileSync(path.join(root, file))).toEqual(before.get(file));
    expect(fs.statSync(path.join(root, target)).isDirectory()).toBe(true);
    const repeated = applyRetirement(root, manifest, true);
    expect(repeated).toMatchObject({ ok: true, removed: [] });
    expect(new Set(repeated.absent)).toEqual(new Set(legacyFiles));
  }, 15_000);

  it("requires a generated filename even when an artifact record recognizes the content", () => {
    const root = legacyFixture();
    const arbitrary = `${target}/reports/personal.md`;
    write(root, secondReport, "old generated body without an envelope");
    write(root, arbitrary, "personal notes");
    const db = new Database(path.join(root, database));
    const statement = db.prepare(
      "INSERT INTO artifact (task_id, run_id, type, title, path_or_url) VALUES (1, 1, 'markdown_report', 'Agent Readiness Sweep', ?)"
    );
    statement.run(path.join(root, secondReport));
    statement.run(path.join(root, arbitrary));
    db.close();
    const manifest = previewRetirement(root);
    expect(manifest.files.map((file) => file.path)).toContain(secondReport);
    expect(manifest.files.map((file) => file.path)).not.toContain(arbitrary);
    expect(applyRetirement(root, manifest, true).ok).toBe(true);
    expect(fs.readFileSync(path.join(root, arbitrary), "utf8")).toBe("personal notes");
  });

  it("can retire envelope-identified reports when the old database is already absent", () => {
    const root = temporaryRoot();
    write(root, firstReport, reportBody);
    write(root, `${database}-wal`, "orphan sidecar");
    const manifest = previewRetirement(root);
    expect(manifest.files.map((entry) => entry.path)).toEqual([firstReport]);
    expect(applyRetirement(root, manifest, true).ok).toBe(true);
    expect(fs.readFileSync(path.join(root, `${database}-wal`), "utf8")).toBe("orphan sidecar");
  });

  it("rejects malformed, tampered, root-rebound, duplicate, escaped and protected manifests", () => {
    const root = legacyFixture();
    const manifest = previewRetirement(root);
    expect(() => applyRetirement(root, { ...manifest, extra: true }, true)).toThrow("schema");
    expect(() => applyRetirement(root, { ...manifest, files: [] }, true)).toThrow("digest");
    expect(() => applyRetirement(temporaryRoot(), manifest, true)).toThrow(
      "different managed-state root"
    );
    for (const badPath of [
      "../outside",
      "/tmp/file",
      "history/agent-ops.db",
      `${target}/../agent-ops.db`,
      `${target}/reports/notes.md`
    ]) {
      const edited = structuredClone(manifest);
      edited.files[0]!.path = badPath;
      expect(() => applyRetirement(root, reseal(edited), true)).toThrow("manifest target");
    }
    const duplicate = structuredClone(manifest);
    duplicate.files.push(duplicate.files[0]!);
    expect(() => applyRetirement(root, reseal(duplicate), true)).toThrow("duplicate");
    const noDirectories = { ...manifest, directories: [] };
    expect(applyRetirement(root, reseal(noDirectories), true)).toMatchObject({
      ok: false,
      removed: []
    });
    expect(fs.existsSync(path.join(root, database))).toBe(true);
  });

  it("rejects same-size changes and inode replacements before deleting anything", () => {
    for (const replace of [false, true]) {
      const root = legacyFixture();
      const manifest = previewRetirement(root);
      const file = path.join(root, firstReport);
      const original = fs.readFileSync(file);
      if (replace) {
        fs.renameSync(file, `${file}.saved`);
        fs.writeFileSync(file, original);
      } else fs.writeFileSync(file, reportBody.replace("Fixture", "Changed"));
      const result = applyRetirement(root, manifest, true);
      expect(result).toMatchObject({ ok: false, removed: [] });
      expect(!result.ok && result.error).toContain("Stale file");
      expect(fs.existsSync(path.join(root, database))).toBe(true);
    }
  });

  it("rejects a new recognized file or omitted sidecar even with a recomputed digest", () => {
    const root = legacyFixture();
    const manifest = previewRetirement(root);
    write(root, `${database}-shm`, Buffer.alloc(32));
    const result = applyRetirement(root, manifest, true);
    expect(result).toMatchObject({ ok: false, removed: [] });
    expect(!result.ok && result.error).toContain("Stale inventory");
    const fresh = previewRetirement(root);
    fresh.files = fresh.files.filter((entry) => entry.kind !== "sidecar");
    expect(applyRetirement(root, reseal(fresh), true)).toMatchObject({ ok: false, removed: [] });
  });

  it("rejects symlinked roots, parents and files without following them", () => {
    for (const relative of ["targets", target, `${target}/reports`, firstReport, database]) {
      const root = legacyFixture();
      const manifest = previewRetirement(root);
      const original = path.join(root, relative);
      const saved = `${original}.saved`;
      fs.renameSync(original, saved);
      fs.symlinkSync(saved, original);
      expect(() => previewRetirement(root)).toThrow("Symlink");
      expect(() => applyRetirement(root, manifest, true)).toThrow("Symlink");
      expect(fs.existsSync(saved)).toBe(true);
    }
    const root = legacyFixture();
    const parent = temporaryRoot();
    const link = path.join(parent, "alias");
    fs.symlinkSync(root, link);
    expect(() => previewRetirement(link)).toThrow("Symlink");
    expect(() => previewRetirement(path.join(link, "targets"))).toThrow("Symlink");
  });

  it("rejects hard-linked recognized files and schemas with extra or wrong tables", () => {
    const linked = legacyFixture();
    fs.linkSync(path.join(linked, firstReport), path.join(linked, "report-copy"));
    expect(() => previewRetirement(linked)).toThrow("single-link");
    for (const sql of [
      "CREATE TABLE interaction (id TEXT)",
      "CREATE TABLE sqlitexhidden (id TEXT)",
      "ALTER TABLE run ADD COLUMN extra TEXT"
    ]) {
      const root = legacyFixture();
      const db = new Database(path.join(root, database));
      db.exec(sql);
      db.close();
      expect(() => previewRetirement(root)).toThrow("Unexpected legacy schema");
      expect(fs.existsSync(path.join(root, firstReport))).toBe(true);
    }
  });

  it.each(["BEGIN IMMEDIATE", "BEGIN; SELECT * FROM run"])(
    "refuses a database held by another process: %s",
    async (transaction) => {
      const root = legacyFixture();
      const manifest = previewRetirement(root);
      await withDatabaseHolder(root, transaction, () => {
        expect(() => previewRetirement(root)).toThrow(/locked|busy/i);
        const result = applyRetirement(root, manifest, true);
        expect(result).toMatchObject({ ok: false, removed: [] });
        expect(new Set(result.remaining)).toEqual(new Set([database, firstReport]));
      });
      expect(applyRetirement(root, previewRetirement(root), true).ok).toBe(true);
    }
  );

  it("inspects a WAL-mode legacy database without creating SQLite sidecars", () => {
    const root = legacyFixture();
    const db = new Database(path.join(root, database));
    db.pragma("journal_mode = WAL");
    db.close();
    const before = fs.readFileSync(path.join(root, database));
    const manifest = previewRetirement(root);
    expect(manifest.files.map((entry) => entry.path)).toContain(database);
    expect(fs.readFileSync(path.join(root, database))).toEqual(before);
    expect(fs.readdirSync(path.join(root, target)).sort()).toEqual(["agent-ops.db", "reports"]);
    expect(applyRetirement(root, manifest, true)).toMatchObject({ ok: true });
  });

  it("refuses cleanup when the open-file probe is unavailable", () => {
    const root = legacyFixture();
    const manifest = previewRetirement(root);
    vi.stubEnv("PATH", path.join(root, "no-executables"));
    expect(() => previewRetirement(root)).toThrow("lsof must be available");
    expect(applyRetirement(root, manifest, true)).toMatchObject({ ok: false, removed: [] });
    expect(fs.existsSync(path.join(root, database))).toBe(true);
  });

  it("reads committed WAL artifacts without mutation and can finish after WAL removal", async () => {
    const root = legacyFixture();
    write(root, secondReport, "legacy report recorded only in WAL");
    const reportPath = path.join(root, secondReport).replace(/'/g, "''");
    await withDatabaseHolder(
      root,
      `
      PRAGMA journal_mode = WAL;
      PRAGMA wal_autocheckpoint = 0;
      INSERT INTO artifact (task_id, run_id, type, title, path_or_url)
        VALUES (1, 2, 'markdown_report', 'Agent Readiness Sweep', '${reportPath}');
      BEGIN IMMEDIATE;
    `,
      () => {
        expect(() => previewRetirement(root)).toThrow("Busy legacy database");
      }
    );
    const files = [database, `${database}-wal`, `${database}-shm`];
    const before = files.map((file) => fs.readFileSync(path.join(root, file)));
    const manifest = previewRetirement(root);
    expect(manifest.files.map((entry) => entry.path)).toContain(secondReport);
    files.forEach((file, index) =>
      expect(fs.readFileSync(path.join(root, file)).equals(before[index]!)).toBe(true)
    );
    const originalUnlink = fs.unlinkSync;
    const spy = vi.spyOn(fs, "unlinkSync").mockImplementation((file) => {
      if (file === path.join(root, database)) throw new Error("database unlink denied");
      originalUnlink(file);
    });
    expect(applyRetirement(root, manifest, true)).toMatchObject({
      ok: false,
      remaining: [database],
      failedPath: database
    });
    spy.mockRestore();
    const fresh = previewRetirement(root);
    expect(fresh.files.map((entry) => entry.path)).toEqual([database]);
    expect(applyRetirement(root, fresh, true)).toMatchObject({ ok: true, removed: [database] });
  }, 15_000);

  it("reports exact remaining files after partial failure and supports a fresh inventory", () => {
    const root = legacyFixture();
    write(root, secondReport, "artifact-only legacy report");
    const db = new Database(path.join(root, database));
    db.prepare(
      "INSERT INTO artifact (task_id, run_id, type, title, path_or_url) VALUES (1, 2, 'markdown_report', 'Agent Readiness Sweep', ?)"
    ).run(path.join(root, secondReport));
    db.close();
    write(root, `${database}-journal`, Buffer.alloc(32));
    const manifest = previewRetirement(root);
    const originalUnlink = fs.unlinkSync;
    const spy = vi.spyOn(fs, "unlinkSync").mockImplementation((file) => {
      if (file === path.join(root, secondReport)) throw new Error("injected EACCES");
      originalUnlink(file);
    });
    expect(applyRetirement(root, manifest, true)).toEqual({
      ok: false,
      removed: [firstReport],
      absent: [],
      remaining: [`${database}-journal`, secondReport, database],
      failedPath: secondReport,
      error: "injected EACCES"
    });
    spy.mockRestore();
    const fresh = previewRetirement(root);
    expect(fresh.files.map((entry) => entry.path)).not.toContain(firstReport);
    expect(applyRetirement(root, fresh, true)).toMatchObject({ ok: true, remaining: [] });
  });

  it("preserves database identity after a sidecar unlink fails", () => {
    const root = legacyFixture();
    for (const suffix of ["-journal", "-shm", "-wal"])
      write(root, `${database}${suffix}`, Buffer.alloc(32));
    const manifest = previewRetirement(root);
    const originalUnlink = fs.unlinkSync;
    const spy = vi.spyOn(fs, "unlinkSync").mockImplementation((file) => {
      if (file === path.join(root, `${database}-shm`)) throw new Error("sidecar denied");
      originalUnlink(file);
    });
    expect(applyRetirement(root, manifest, true)).toMatchObject({
      ok: false,
      removed: [firstReport, `${database}-journal`],
      remaining: [`${database}-shm`, `${database}-wal`, database]
    });
    spy.mockRestore();
    expect(previewRetirement(root).files.map((entry) => entry.path)).toContain(database);
    expect(applyRetirement(root, manifest, true)).toMatchObject({
      ok: true,
      absent: [firstReport, `${database}-journal`]
    });
  }, 15_000);

  it("revalidates file identity and parent containment before the next unlink", () => {
    for (const mutation of ["file", "parent"]) {
      const root = legacyFixture();
      write(root, secondReport, reportBody);
      const manifest = previewRetirement(root);
      const originalUnlink = fs.unlinkSync;
      const spy = vi.spyOn(fs, "unlinkSync").mockImplementation((file) => {
        originalUnlink(file);
        if (file !== path.join(root, firstReport)) return;
        if (mutation === "file") fs.writeFileSync(path.join(root, secondReport), "replacement");
        else {
          const reports = path.join(root, target, "reports");
          fs.renameSync(reports, `${reports}.saved`);
          fs.symlinkSync(`${reports}.saved`, reports);
        }
      });
      const result = applyRetirement(root, manifest, true);
      expect(result).toMatchObject({ ok: false, removed: [firstReport] });
      expect(result.remaining).toEqual([secondReport, database]);
      expect(spy.mock.calls.filter(([file]) => String(file).startsWith(`${root}/`))).toHaveLength(
        1
      );
      expect(fs.existsSync(path.join(root, database))).toBe(true);
      spy.mockRestore();
    }
  });

  it("exercises public preview/apply syntax with a reviewed JSON file in temporary state", () => {
    const root = legacyFixture();
    const script = path.resolve(import.meta.dirname, "../scripts/retire-legacy-state.ts");
    const command = (args: string[]) =>
      execFileSync(process.execPath, ["--import", "tsx", script, ...args], {
        encoding: "utf8",
        stdio: ["ignore", "pipe", "pipe"]
      });
    const preview = command(["preview", "--root", root]);
    const manifest = path.join(temporaryRoot(), "reviewed.json");
    fs.writeFileSync(manifest, preview);
    expect(() => command(["apply", "--root", root, "--manifest", manifest])).toThrow();
    const result: unknown = JSON.parse(
      command(["apply", "--root", root, "--manifest", manifest, "--writers-stopped"])
    );
    expect(result).toMatchObject({ ok: true, remaining: [] });
  });
});
