from datetime import UTC, datetime
from pathlib import Path

from agent_ops_kit.checks import CheckFinding, CheckNotice, CheckSignal
from agent_ops_kit.interpretation import SweepInterpretation


def write_sweep_report(
    repo_path: Path,
    run_id: int,
    findings: list[CheckFinding],
    passed_signals: list[CheckSignal] | None = None,
    informational_notices: list[CheckNotice] | None = None,
    interpretation: SweepInterpretation | None = None,
) -> Path:
    reports_dir = repo_path.resolve() / ".agent-readiness" / "reports"
    reports_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
    report_path = reports_dir / f"{timestamp}-{run_id}-readiness-sweep.md"
    report_path.write_text(
        _render_report(
            repo_path,
            findings,
            passed_signals or [],
            informational_notices or [],
            interpretation,
        ),
        encoding="utf-8",
    )
    return report_path


def _render_report(
    repo_path: Path,
    findings: list[CheckFinding],
    passed_signals: list[CheckSignal] | None = None,
    informational_notices: list[CheckNotice] | None = None,
    interpretation: SweepInterpretation | None = None,
) -> str:
    rows = "\n".join(
        f"| {finding.severity} | {finding.category} | {finding.title} | "
        f"{finding.recommendation} | {_format_evidence(finding.file_path, finding.evidence)} |"
        for finding in findings
    )
    if not rows:
        rows = "| info | readiness | No findings | The repo has the core agent-readiness signals. | - |"

    signal_rows = "\n".join(
        f"| {signal.category} | {signal.title} | "
        f"{_format_evidence(signal.file_path, signal.evidence)} |"
        for signal in passed_signals or []
    )
    if not signal_rows:
        signal_rows = "| readiness | No passed signals recorded | - |"

    standards_not_found_rows = "\n".join(
        f"| {notice.title} | {notice.note} | {_format_evidence(None, notice.evidence)} |"
        for notice in informational_notices or []
        if notice.category == "standards"
    )
    if not standards_not_found_rows:
        standards_not_found_rows = "| No optional standards gaps recorded | - | - |"

    interpretation_section = _render_interpretation(interpretation)

    return f"""# Agent Readiness Sweep

Repository: `{repo_path.resolve()}`

This report was generated by Agent Ops Kit. The sweep is read-only for source files.

## Findings

| Severity | Category | Finding | Recommendation | Evidence |
| --- | --- | --- | --- | --- |
{rows}

## Passed Signals

| Category | Signal | Evidence |
| --- | --- | --- |
{signal_rows}

## Standards Not Found

These are informational. Missing standards in this section may not be needed for this repo.

| Standard | Note | Evidence |
| --- | --- | --- |
{standards_not_found_rows}

{interpretation_section}

## Next Step

Fix the highest-severity findings first, then rerun:

```bash
agent-ops sweep {repo_path.resolve()}
```
"""


def _render_interpretation(interpretation: SweepInterpretation | None) -> str:
    if interpretation is None:
        return ""

    output = interpretation.output
    if output is None:
        if interpretation.status == "skipped" and interpretation.error == "missing_minimax_api_key":
            summary = "Interpretation was requested, but MINIMAX_API_KEY is not set."
        else:
            summary = interpretation.error or "No interpretation output was produced."
    else:
        required = _format_markdown_list(output.required_fixes)
        optional = _format_markdown_list(output.optional_improvements)
        summary = "\n".join(
            [
                f"**Overall judgment:** {output.overall_judgment}",
                "",
                "**Required fixes:**",
                required,
                "",
                "**Optional improvements:**",
                optional,
                "",
                f"**Next step:** {output.next_step}",
            ]
        )

    cost = "-" if interpretation.usage.cost is None else str(interpretation.usage.cost)
    error_row = ""
    if interpretation.error:
        error_row = f"| Error | {_escape_table_cell(interpretation.error)} |\n"

    return f"""## LLM Interpretation

{summary}

### LLM Usage

| Metric | Value |
| --- | --- |
| Status | {interpretation.status} |
| Provider | {interpretation.provider} |
| Model | {interpretation.model} |
| Requests | {interpretation.usage.requests} |
| Input tokens | {interpretation.usage.input_tokens} |
| Output tokens | {interpretation.usage.output_tokens} |
| Total tokens | {interpretation.usage.total_tokens} |
| Cost | {cost} |
{error_row}"""


def _format_markdown_list(items: list[str]) -> str:
    if not items:
        return "- None"
    return "\n".join(f"- {item}" for item in items)


def _format_evidence(file_path: str | None, evidence: dict[str, object] | None) -> str:
    if file_path and not evidence:
        return file_path
    if not evidence:
        return "-"

    parts: list[str] = []
    if file_path:
        parts.append(f"path={file_path}")
    for key, value in evidence.items():
        if isinstance(value, list):
            rendered = ", ".join(str(item) for item in value)
        else:
            rendered = str(value)
        parts.append(f"{key}={rendered}")
    return _escape_table_cell("; ".join(parts))


def _escape_table_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")
