from datetime import UTC, datetime
from pathlib import Path

from agent_ops_kit.checks import CheckFinding


def write_sweep_report(
    repo_path: Path,
    run_id: int,
    findings: list[CheckFinding],
) -> Path:
    reports_dir = repo_path.resolve() / ".agent-readiness" / "reports"
    reports_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
    report_path = reports_dir / f"{timestamp}-{run_id}-readiness-sweep.md"
    report_path.write_text(_render_report(repo_path, findings), encoding="utf-8")
    return report_path


def _render_report(repo_path: Path, findings: list[CheckFinding]) -> str:
    rows = "\n".join(
        f"| {finding.severity} | {finding.category} | {finding.title} | {finding.recommendation} |"
        for finding in findings
    )
    if not rows:
        rows = "| info | readiness | No findings | The repo has the core agent-readiness signals. |"

    return f"""# Agent Readiness Sweep

Repository: `{repo_path.resolve()}`

This report was generated by Agent Ops Kit. The sweep is read-only for source files.

## Findings

| Severity | Category | Finding | Recommendation |
| --- | --- | --- | --- |
{rows}

## Next Step

Fix the highest-severity findings first, then rerun:

```bash
agent-ops sweep {repo_path.resolve()}
```
"""
