import path from "node:path";

import type { WorkspaceSummary } from "../workspaces/types.js";

export function renderReportEnvelope(
  repoPath: string,
  body: string,
  options: { workspace?: WorkspaceSummary; contextSections?: string[] } = {}
): string {
  const repository = options.workspace?.origin ?? path.resolve(repoPath);
  const metadata = [
    `Repository: \`${repository}\``,
    ...(options.workspace
      ? [
          `Source: \`${options.workspace.source}\``,
          `Ref: \`${options.workspace.ref}\``,
          `Commit: \`${options.workspace.commitSha}\``,
          `Workspace: \`${path.resolve(repoPath)}\``
        ]
      : [])
  ].join("\n");
  const context = (options.contextSections ?? []).filter(Boolean).join("\n\n");

  return `# Agent Readiness Sweep

${metadata}

This report was generated by Agent Ops Kit through a read-only workflow.

${context}

${body.trim()}
`;
}
