import fs from "node:fs";
import path from "node:path";

import { redactApplicationText } from "../harness/redaction.js";
import { historyArtifactsPath } from "../workspaces/storage.js";
import type { WorkspaceSummary } from "../workspaces/types.js";

export function writeSweepReport(runId: number, markdown: string): string {
  const root = fs.realpathSync(historyArtifactsPath());
  const reportPath = path.join(root, `${runId}-readiness-sweep.md`);
  fs.writeFileSync(reportPath, redactApplicationText(markdown), {
    encoding: "utf8",
    mode: 0o600,
    flag: "wx"
  });
  return reportPath;
}

export function renderReportEnvelope(
  repoPath: string,
  body: string,
  options: { workspace?: WorkspaceSummary; contextSections?: string[] } = {}
): string {
  const repository = options.workspace?.origin ?? path.resolve(repoPath);
  const metadata = [
    `Repository: \`${repository}\``,
    ...(options.workspace
      ? [
          `Source: \`${options.workspace.source}\``,
          `Ref: \`${options.workspace.ref}\``,
          `Commit: \`${options.workspace.commitSha}\``,
          `Workspace: \`${path.resolve(repoPath)}\``
        ]
      : [])
  ].join("\n");
  const context = (options.contextSections ?? []).filter(Boolean).join("\n\n");

  return `# Agent Readiness Sweep

${metadata}

This report was generated by Agent Ops Kit through a read-only workflow.

${context}

${body.trim()}
`;
}
